### ISSUE TITLE
Updating EA's from JAMF Viewer

### ISSUE THREAD

**Issue by norman-chan** [krypted/jamf_zendesk#6]
Not sure if this is the place to ask but is there any plan to integrate the ability to update an EA?  The purpose would be to tag a JAMF asset as broken, in repair, etc.. Would be super helpful to be able to manage these EA's as tickets come in about device replacements, etc..

**Comment by yuresko** [comment]
Hey! Absolutely... This v1.1 is certainly the first iteration of the integration and I hope either myself of someone in the community can enhance the feature set in the future. As it's not officially a Jamf product, and it being open-source, it can be adjusted/modified by anyone! I'd love for this to be implemented!
